# hw10

1. 创建并储存三维数组，该数组有6层，每层是4*2阶矩阵，并以适当的步长按降序将4.8-0.1填充到数组中。然后按照顺序提取所有层的第二列第四行和第一行的所有元素，并存储为一个新的对象。

In [2]:
 
A=array(data=seq(from = 4.8,to = 0.1,by = -0.1),dim=c(4,2,6))
print(A)
B<-list(A[4,2,],A[1,,])
B

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1



[[1]]
[1] 4.1 3.3 2.5 1.7 0.9 0.1

[[2]]
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  4.8  4.0  3.2  2.4  1.6  0.8
[2,]  4.4  3.6  2.8  2.0  1.2  0.4

2. (a) Store the following vector of 15 values as an object in your workspace: c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1). Identify the following elements:

i. Those equal to 6

ii. Those greater than or equal to 6

iii. Those less than 6 + 2

iv. Those not equal to 6

In [2]:
C<-c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1)
C[C==6]
C[C>=6]
C[C<=6+2]
C[C!=6]


[1] 6 6 6 6 6

[1] 6 9 7 6 7 9 6 6 6 7 9

[1] 6 7 3 6 7 6 3 6 6 7 1 1

[1] 9 7 3 7 9 3 7 1 9 1

(b) Create a new vector from the one used in 2(a) by deleting its first three elements. With this new vector, fill a 2 * 2 * 3 array. Examine the array for the following entries:
i. Those less than or equal to 6 divided by 2, plus 4
ii. Those less than or equal to 6 divided by 2, plus 4, after increasing every element in the array by 2

In [4]:
D<-array(C[-(1:3)],dim=c(2,2,3))
print(D)
D[D<=(6/2+4)]
D[(D+2)<=(6/2+4)]


, , 1

     [,1] [,2]
[1,]    3    7
[2,]    6    9

, , 2

     [,1] [,2]
[1,]    6    6
[2,]    3    6

, , 3

     [,1] [,2]
[1,]    7    9
[2,]    1    1



[1] 3 6 7 6 3 6 6 7 1 1

[1] 3 3 1 1

(c) Check whether any of the values of the logical arrays created in 2(b) are TRUE. If they are, check whether they are all TRUE.

In [24]:
any(D<=(6/4+2))
all(D<=(6/4+2))

[1] TRUE

[1] FALSE

In [25]:
any((D+2)<=(6/4+2))
all((D+2)<=(6/4+2))

[1] TRUE

[1] FALSE

3 (a) Store this vector of 10 values: foo <- c(7,5,6,1,2,10,8,3,8,2). Then, do the following:
i. Extract the elements greater than or equal to 5, storing the result as bar.
ii. Display the vector containing those elements from foo that remain after omitting all elements that are greater than or equal to 5.


In [29]:
foo <- c(7,5,6,1,2,10,8,3,8,2)
bar<-foo[foo>=5]
bar
foo_ommit<-foo[!(foo>=5)]
foo_ommit

[1]  7  5  6 10  8  8

[1] 1 2 3 2

(b) Use bar from 3(a)(i) to construct a 2*3 matrix called baz, filling in a row-wise fashion. Then, do the following:
i. Replace any elements that are equal to 8 with the squared value of the element in row 1, column 2 of baz itself.
ii. Confirm that all values in baz are now less than or equal to 25 and greater than 4.

In [40]:
print(bar)
baz<-matrix(data=bar,nrow=2,byrow=TRUE)
print(baz)

baz[baz==8]<-baz[1,2]^2
print(baz)

print(all(baz<=25 & baz>4))

[1]  7  5  6 10  8  8
     [,1] [,2] [,3]
[1,]    7    5    6
[2,]   10    8    8
     [,1] [,2] [,3]
[1,]    7    5    6
[2,]   10   25   25
[1] TRUE
