# hw13

1. Write R code that takes a square character matrix and checks if any of the character strings on the diagonal (top left to bottom right) begin with the letter g, lowercase or uppercase. If satisfied, these specific entries should be overwritten with the string "HERE". Otherwise, the entire matrix should be replaced with an identity matrix of the same dimensions. try your code on the following matrices, checking the result each time:
i. mymat <- matrix(as.character(1:16),4,4)
ii. mymat <- matrix(c("DANDELION","Hyacinthus","Gerbera","MARIGOLD", "geranium","ligularia","Pachysandra","SNAPDRAGON","GLADIOLUS"),3,3)
iii. mymat <- matrix(c("GREAT","exercises","right","here"),2,2,byrow=T)

In [1]:
process_matrix <- function(m) {
  # 获取主对角线索引
  diag_indices <- 1:nrow(m)
  # 获取主对角线元素
  diag_elements <- m[cbind(diag_indices, diag_indices)]
  
  # 检查是否有以 g 或 G 开头的元素
  matches <- grepl("^[gG]", diag_elements)
  
  if (any(matches)) {
    # 将符合条件的位置替换为 "HERE"
    m[cbind(diag_indices[matches], diag_indices[matches])] <- "HERE"
    return(m)
  } else {
    # 返回相同大小的单位矩阵
    return(diag(1, nrow(m)))
  }
}


In [2]:
# i
mymat1 <- matrix(as.character(1:16), 4, 4)
print(process_matrix(mymat1))


     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1


In [3]:
# ii
mymat2 <- matrix(c("DANDELION", "Hyacinthus", "Gerbera", 
                   "MARIGOLD", "geranium", "ligularia", 
                   "Pachysandra", "SNAPDRAGON", "GLADIOLUS"), 3, 3)
print(process_matrix(mymat2))



     [,1]         [,2]        [,3]         
[1,] "DANDELION"  "MARIGOLD"  "Pachysandra"
[2,] "Hyacinthus" "HERE"      "SNAPDRAGON" 
[3,] "Gerbera"    "ligularia" "HERE"       


In [4]:
# iii
mymat3 <- matrix(c("GREAT", "exercises", "right", "here"), 2, 2, byrow=TRUE)
print(process_matrix(mymat3))


     [,1]    [,2]       
[1,] "HERE"  "exercises"
[2,] "right" "here"     


2. Assume the object mynum will only ever be a single integer between 0 and 9. Use ifelse and switch to produce a command that takes in mynum and returns a matching character string for all possible values 0, 1, . . . , 9. Supplied with 3, for example, it should return "three"; supplied with 0, it should return "zero".

In [5]:
mynum <- 3  

# 使用 ifelse + switch 组合
result <- ifelse(mynum %in% 0:9,
                 switch(as.character(mynum),
                        "0" = "zero",
                        "1" = "one",
                        "2" = "two",
                        "3" = "three",
                        "4" = "four",
                        "5" = "five",
                        "6" = "six",
                        "7" = "seven",
                        "8" = "eight",
                        "9" = "nine"),
                 NA)

print(result)


[1] "three"


3. We used the command switch(EXPR=mystring,Homer=12,Marge=34,Bart=56,Lisa=78,Maggie=90, NA) to return a number based on the supplied value of a single character string. This line won’t work if mystring is a character vector. Write some code that will take a character vector and return a vector of the appropriate numeric values. Test it on the following vector:
c("Peter","Homer","Lois","Stewie","Maggie","Bart")

In [6]:
names_vec <- c("Peter", "Homer", "Lois", "Stewie", "Maggie", "Bart")

result <- sapply(names_vec, function(mystring) {
  switch(mystring,
         "Homer" = 12,
         "Marge" = 34,
         "Bart" = 56,
         "Lisa" = 78,
         "Maggie" = 90,
         NA)  
})

print(result)


 Peter  Homer   Lois Stewie Maggie   Bart 
    NA     12     NA     NA     90     56 


4. Convert the following for loop to an implicit loop that does exactly the same thing:
matlist <- list(matrix(c(T,F,T,T),2,2),matrix(c("a","c","b","z","p","q"),3,2),matrix(1:8,2,4))
matlist
for(i in 1:length(matlist)){
matlist[[i]] <- t(matlist[[i]])
}
matlist

In [7]:
matlist <- list(
  matrix(c(T,F,T,T), 2, 2),
  matrix(c("a","c","b","z","p","q"), 3, 2),
  matrix(1:8, 2, 4)
)

print(matlist)
print("-----")
for(i in 1:length(matlist)){
  matlist[[i]] <- t(matlist[[i]])
}
print(matlist)

[[1]]
      [,1] [,2]
[1,]  TRUE TRUE
[2,] FALSE TRUE

[[2]]
     [,1] [,2]
[1,] "a"  "z" 
[2,] "c"  "p" 
[3,] "b"  "q" 

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

[1] "-----"
[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8

[1] "-----"
[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8



In [8]:
matlist <- list(
  matrix(c(T,F,T,T), 2, 2),
  matrix(c("a","c","b","z","p","q"), 3, 2),
  matrix(1:8, 2, 4)
)

matlist <- lapply(matlist, t)

print(matlist)

[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8



5. Write a recursive version of a function implementing the nonnegative integer factorial operator. The stopping rule should return the value 1 if the supplied integer is 0. Confirm that your function produces the same results as earlier.
i. 5 factorial is 120.
ii. 120 factorial is 479;001;600.
iii. 0 factorial is 1.

In [9]:
myfactorial <- function(n) {
  if (n == 0) {
    return(1)
  } else {
    return(n * myfactorial(n - 1))
  }
}

factorial5 <- myfactorial(5)
print(factorial5)
factorial120 <- myfactorial(120)
print(factorial120)
factorial0<- myfactorial(0)
print(factorial0)


[1] 120
[1] 6.689503e+198
[1] 6.689503e+198
[1] 1
