#### R中的简单操作

In [ ]:
2+3

5

In [ ]:
14/6+5

7.333333333333334

In [ ]:
2^3

1

In [ ]:
sqrt(9)

NameError: name 'sqrt' is not defined

In [ ]:
sqrt(x=5.311)

[1] 2.304561

In [ ]:
10^2+3*60/8-3

[1] 119.5

In [ ]:
log(x=243)  #自然对数

[1] 5.493061

In [ ]:
log(x=243,base=3)

[1] 5

In [ ]:
exp(x=3)

[1] 20.08554

In [ ]:
0.0000002533 #科学计数法

[1] 2.533e-07

In [ ]:
x <- -5
x

[1] -5

In [ ]:
x = x + 1
x

[1] -4

In [ ]:
mynumber = 45.2
y <- mynumber*x
y

[1] -180.8

In [ ]:
ls() #当前工作空间中包含的内容

[1] "mynumber" "x"        "y"

#### 向量

In [ ]:
myvec <- c(1,3,1,42)  # c for concatenate
myvec

[1]  1  3  1 42

In [ ]:
foo <- 32.1
myvec2 <- c(3,-3,2,3.45,1e+03,64^0.5,2+(3-1.1)/9.44,foo)  
myvec2

[1]    3.000000   -3.000000    2.000000    3.450000 1000.000000    8.000000
[7]    2.201271   32.100000

In [ ]:
myvec3 <- c(myvec,myvec2)
myvec3

[1]    1.000000    3.000000    1.000000   42.000000    3.000000   -3.000000
 [7]    2.000000    3.450000 1000.000000    8.000000    2.201271   32.100000

#### 序列，重复，排序和长度

In [ ]:
3:27  #生成从3到27的向量

[1]  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27

In [ ]:
foo <- 5.3
bar <- foo:(-47+1.5)  #生成从5.3到-47+1.5的向量
head(bar)

[1] 5.3 4.3 3.3 2.3 1.3 0.3

In [ ]:
seq(from=3,to=27,by=3)  #从from开始，间隔3，最大为27的序列

[1]  3  6  9 12 15 18 21 24 27

In [ ]:
head(seq(from=3,to=27,length.out=40)) #从3开始，到27结束，长度为40的序列

[1] 3.000000 3.615385 4.230769 4.846154 5.461538 6.076923

In [ ]:
foo <- 5.3
myseq <- seq(from=foo,to=(-47+1.5),by=-2.4) #递减序列
head(myseq)

[1]  5.3  2.9  0.5 -1.9 -4.3 -6.7

In [ ]:
myseq2 <- seq(from=foo,to=(-47+1.5),length.out=5)
myseq2

[1]   5.3  -7.4 -20.1 -32.8 -45.5

In [ ]:
rep(x=1,times=4)   #repeat

[1] 1 1 1 1

In [ ]:
rep(x=c(3,62,8.3),times=3)

[1]  3.0 62.0  8.3  3.0 62.0  8.3  3.0 62.0  8.3

In [ ]:
rep(x=c(3,62,8.3),times=3,each=2)

[1]  3.0  3.0 62.0 62.0  8.3  8.3  3.0  3.0 62.0 62.0  8.3  8.3  3.0  3.0 62.0
[16] 62.0  8.3  8.3

In [ ]:
foo <- 4
c(3,8.3,rep(x=32,times=foo),seq(from=-2,to=1,length.out=foo+1))

[1]  3.00  8.30 32.00 32.00 32.00 32.00 -2.00 -1.25 -0.50  0.25  1.00

In [ ]:
sort(x=c(2.5,-1,-10,3.44),decreasing=FALSE)  #排序

[1] -10.00  -1.00   2.50   3.44

In [ ]:
sort(x=c(2.5,-1,-10,3.44),decreasing=TRUE)

[1]   3.44   2.50  -1.00 -10.00

In [ ]:
length(x=c(3,2,8,1)) #向量长度

[1] 4

In [ ]:
length(x=5:13)

[1] 9

In [ ]:
foo <- 4
bar <- c(3,8.3,rep(x=32,times=foo),seq(from=-2,to=1,length.out=foo+1))
length(x=bar)

[1] 11

#### 子集和元素的提取

In [ ]:
myvec <- c(5,-2.3,4,4,4,6,8,10,40221,-8)
length(x=myvec)
myvec[1]           #下标从1开始

[1] 10

[1] 5

In [ ]:
foo <- myvec[2]
foo

[1] -2.3

In [ ]:
myvec[length(x=myvec)] #最后一个元素

[1] -8

In [ ]:
myvec.len <- length(x=myvec)
bar <- myvec[myvec.len-1] #倒数第二个元素
bar

[1] 40221

In [ ]:
myvec[2:3]

[1] -2.3  4.0

In [ ]:
myvec[-1]  #删除第一个元素，注意与python的区别，另外，此时，myvec本身并没有变化

[1]    -2.3     4.0     4.0     4.0     6.0     8.0    10.0 40221.0    -8.0

In [ ]:
myvec

[1]     5.0    -2.3     4.0     4.0     4.0     6.0     8.0    10.0 40221.0
[10]    -8.0

In [ ]:
baz <- myvec[-2]  #删除第二个元素并且赋值给baz
baz

[1]     5     4     4     4     6     8    10 40221    -8

In [ ]:
qux <- myvec[-(myvec.len-1)]  #删除倒数第二个元素
qux

[1]  5.0 -2.3  4.0  4.0  4.0  6.0  8.0 10.0 -8.0

In [ ]:
c(qux[-length(x=qux)],bar,qux[length(x=qux)])  #重新构造myvec，bar是myvec的倒数第二个元素

[1]     5.0    -2.3     4.0     4.0     4.0     6.0     8.0    10.0 40221.0
[10]    -8.0

In [ ]:
1:4
foo <- myvec[1:4]
foo

[1] 1 2 3 4

[1]  5.0 -2.3  4.0  4.0

In [ ]:
myvec[c(1,3,5)]

[1] 5 4 4

In [ ]:
length(x=foo):2
foo[length(foo):2]

[1] 4 3 2

[1]  4.0  4.0 -2.3

In [ ]:
indexes <- c(4,rep(x=2,times=3),1,1,2,3:1)
indexes
foo[indexes]

[1] 4 2 2 2 1 1 2 3 2 1

[1]  4.0 -2.3 -2.3 -2.3  5.0  5.0 -2.3  4.0 -2.3  5.0

In [ ]:
foo[-c(1,3)]  #删除第一个和第三个元素

[1] -2.3  4.0

In [ ]:
bar <- c(3,2,4,4,1,2,4,1,0,0,5)
bar[1] <- 6
bar

[1] 6 2 4 4 1 2 4 1 0 0 5

In [ ]:
bar[c(2,4,6)] <- c(-2,-0.5,-1)
bar

[1]  6.0 -2.0  4.0 -0.5  1.0 -1.0  4.0  1.0  0.0  0.0  5.0

In [ ]:
bar[7:10] <- 100
bar

[1]   6.0  -2.0   4.0  -0.5   1.0  -1.0 100.0 100.0 100.0 100.0   5.0

#### 向量操作

In [ ]:
foo <- 5.5:0.5
foo
foo-c(2,4,6,8,10,12)   #减法

[1] 5.5 4.5 3.5 2.5 1.5 0.5

[1]   3.5   0.5  -2.5  -5.5  -8.5 -11.5

In [ ]:
bar <- c(1,-1)
foo*bar   #向量乘法，此时foo的长度是bar的长度整数倍

[1]  5.5 -4.5  3.5 -2.5  1.5 -0.5

In [ ]:
baz <- c(1,-1,0.5,-0.5)
foo*baz       #此时foo的长度不是bar的长度整数倍

Warning message in foo * baz:
"长的对象长度不是短的对象长度的整倍数"

[1]  5.50 -4.50  1.75 -1.25  1.50 -0.50

In [ ]:
foo-c(2,4,6,8,10)

Warning message in foo - c(2, 4, 6, 8, 10):
"长的对象长度不是短的对象长度的整倍数"

[1]  3.5  0.5 -2.5 -5.5 -8.5 -1.5

In [ ]:
qux <- 3
foo+qux

[1] 8.5 7.5 6.5 5.5 4.5 3.5

In [ ]:
sum(foo)

[1] 18

In [ ]:
prod(foo)  #连乘

[1] 162.4219

In [ ]:
foo[c(1,3,5,6)] <- c(-99,99)   #注意长度不一致如何处理
foo

[1] -99.0   4.5  99.0   2.5 -99.0  99.0

##### 思考题：将华氏度F转化为摄氏度C的公式如下：C=5(F-32)/9, 将华氏45，77，20，19，101，120，212转化为摄氏度

In [ ]:
faren <- c(45,77,20,19,101,120,212)
cel <- 5/9*(faren-32)
cel

[1]   7.222222  25.000000  -6.666667  -7.222222  38.333333  48.888889 100.000000

##### 对向量c(2,4,6)和 c(1,2)进行组合，使用rep和*来创建c(2,4,6,4,8,12)

In [ ]:
foo <- rep(x=c(2,4,6),times=2)*rep(x=c(1,2),each=3)
foo

[1]  2  4  6  4  8 12

#### 定义矩阵

In [ ]:
A <- matrix(data=c(-3,2,893,0.17),nrow=2,ncol=2)
A

[,1] [,2]  
[1,] -3   893.00
[2,]  2     0.17

In [ ]:
matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [ ]:
matrix(data=c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

##### 合并行和列

In [ ]:
rbind(1:3,4:6)   #row bind

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
cbind(c(1,4),c(2,5),c(3,6)) #column bind

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [ ]:
mymat <- rbind(c(1,3,4),5:3,c(100,20,90),11:13)
mymat

[,1] [,2] [,3]
[1,]   1   3    4  
[2,]   5   4    3  
[3,] 100  20   90  
[4,]  11  12   13

In [ ]:
dim(mymat)
nrow(mymat)
ncol(mymat)
dim(mymat)[2]

[1] 4 3

[1] 4

[1] 3

[1] 3

##### 矩阵索引

In [ ]:
A <- matrix(c(0.3,4.5,55.3,91,0.1,105.5,-4.2,8.2,27.9),nrow=3,ncol=3)
A
A[3,2]

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

[1] 105.5

In [ ]:
A[,2]

[1]  91.0   0.1 105.5

In [ ]:
A[1,]

[1]  0.3 91.0 -4.2

In [ ]:
A[2:3,]
A[,c(3,1)]
A[c(3,1),2:3]

[,1] [,2]  [,3]
[1,]  4.5   0.1  8.2
[2,] 55.3 105.5 27.9

[,1] [,2]
[1,] -4.2  0.3
[2,]  8.2  4.5
[3,] 27.9 55.3

[,1]  [,2]
[1,] 105.5 27.9
[2,]  91.0 -4.2

In [ ]:
diag(x=A)   #方阵对角线

[1]  0.3  0.1 27.9

In [ ]:
A[,-2]  #删除第二列

[,1] [,2]
[1,]  0.3 -4.2
[2,]  4.5  8.2
[3,] 55.3 27.9

In [ ]:
A[-1,3:2]   #删除第一行后的第三列和第二列

[,1] [,2] 
[1,]  8.2   0.1
[2,] 27.9 105.5

In [ ]:
A[-1,-2]

[,1] [,2]
[1,]  4.5  8.2
[2,] 55.3 27.9

In [ ]:
A[-1,-c(2,3)]

[1]  4.5 55.3

In [ ]:
B <- A
B[2,] <- 1:3
B

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  1.0   2.0  3.0
[3,] 55.3 105.5 27.9

In [ ]:
B[c(1,3),2] <- 900
B

[,1] [,2] [,3]
[1,]  0.3 900  -4.2
[2,]  1.0   2   3.0
[3,] 55.3 900  27.9

In [ ]:
B[,3] <- B[3,]  #第三列等于第三行
B

[,1] [,2] [,3] 
[1,]  0.3 900   55.3
[2,]  1.0   2  900.0
[3,] 55.3 900   27.9

In [ ]:
B[c(1,3),c(1,3)]
B[c(1,3),c(1,3)] <- c(-7,7)      #按列赋值
B

[,1] [,2]
[1,]  0.3 55.3
[2,] 55.3 27.9

[,1] [,2] [,3]
[1,] -7   900   -7 
[2,]  1     2  900 
[3,]  7   900    7

In [ ]:
B[c(1,3),2:1]
B[c(1,3),2:1] <- c(65,-65,88,-88) #按列赋值
B[c(1,3),2:1]
B

[,1] [,2]
[1,] 900  -7  
[2,] 900   7

[,1] [,2]
[1,]  65   88 
[2,] -65  -88

[,1] [,2] [,3]
[1,]  88   65   -7 
[2,]   1    2  900 
[3,] -88  -65    7

In [ ]:
diag(x=B) <- 0  #注意B的改变
B

[,1] [,2] [,3]
[1,]   0   65   -7 
[2,]   1    0  900 
[3,] -88  -65    0

##### 矩阵运算

In [ ]:
A <- rbind(c(2,5,2),c(6,1,4))
A
t(A)  #转置

[,1] [,2] [,3]
[1,] 2    5    2   
[2,] 6    1    4

[,1] [,2]
[1,] 2    6   
[2,] 5    1   
[3,] 2    4

In [ ]:
t(t(A))

[,1] [,2] [,3]
[1,] 2    5    2   
[2,] 6    1    4

In [ ]:
A <- diag(x=3)   #单位阵
A

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [ ]:
A <- rbind(c(2,5,2),c(6,1,4))
a <- 2
a*A          #数乘

[,1] [,2] [,3]
[1,]  4   10   4   
[2,] 12    2   8

In [ ]:
A <- cbind(c(2,5,2),c(6,1,4))
B <- cbind(c(-2,3,6),c(8.1,8.2,-9.8))
A-B         #减法

[,1] [,2]
[1,]  4   -2.1
[2,]  2   -7.2
[3,] -4   13.8

In [ ]:
A <- rbind(c(2,5,2),c(6,1,4))
dim(A)
B <- cbind(c(3,-1,1),c(-3,1,5))
dim(B)

[1] 2 3

[1] 3 2

In [ ]:
A%*%B  #矩阵乘法

[,1] [,2]
[1,]  3   9   
[2,] 21   3

In [ ]:
B%*%A

[,1] [,2] [,3]
[1,] -12  12   -6  
[2,]   4  -4    2  
[3,]  32  10   22

In [ ]:
A <- matrix(data=c(3,4,1,2),nrow=2,ncol=2)
A
solve(A)  #矩阵的逆

[,1] [,2]
[1,] 3    1   
[2,] 4    2

[,1] [,2]
[1,]  1   -0.5
[2,] -2    1.5

In [ ]:
A%*%solve(A)

[,1] [,2]
[1,] 1    0   
[2,] 0    1

##### 多维数组

In [ ]:
AR <- array(data=1:24,dim=c(3,4,2))
print(AR)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [ ]:
BR <- array(data=rep(x=1:24,times=3),dim=c(3,4,2,3))

In [ ]:
print(BR)

, , 1, 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2, 1

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 1, 2

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2, 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 1, 3

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2, 3

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [ ]:
print(AR[2,,2])

[1] 14 17 20 23


In [ ]:
AR[2,c(3,1),2]

[1] 20 14

In [ ]:
print(AR[1,,])   #4*2

     [,1] [,2]
[1,]    1   13
[2,]    4   16
[3,]    7   19
[4,]   10   22


In [ ]:
BR[2,1,1,3]

[1] 2

In [ ]:
print(BR[1,,,1])

     [,1] [,2]
[1,]    1   13
[2,]    4   16
[3,]    7   19
[4,]   10   22


In [ ]:
print(BR[,,2,])

, , 1

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 3

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [ ]:
print(BR[2,,1,])

     [,1] [,2] [,3]
[1,]    2    2    2
[2,]    5    5    5
[3,]    8    8    8
[4,]   11   11   11
